<?php

/**
 * @file
 * Miscellaneous hook implementations.
 */

/**
 * Implements hook_menu().
 */
function agile_coursepack_menu() {
  $items = array();
  $items['agile/coursepack/splash'] = array(
    'title' => 'Coursepack Splash',
    'description' => 'Coursepack landing page',
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agile_coursepack_splash'),
    'file' => 'includes/coursepack_splash.inc',
    'access arguments' => array('access content'),
  );
  $items['admin/islandora/solution_pack_config/coursepack'] = array(
    'title' => 'Coursepack Configuration',
    'description' => 'Configure the coursepck module.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('agile_coursepack_admin_settings_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_CALLBACK,
  );
  $items['agile_coursepack/add_item'] = array(
    'title' => 'Add item',
    'description' => 'Add digital asset to repository.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('agile_coursepack_add_item_form'),
    'file' => 'includes/add_item.form.inc',
    'type' => MENU_CALLBACK,
  );
  $items['agile_coursepack/add_coursepack'] = array(
    'title' => 'Coursepack Metadata',
    'description' => 'Create or edit coursepack metadata.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('agile_coursepack_add_coursepack_form'),
    'file' => 'includes/agile_create_coursepack.form.inc',
    'type' => MENU_CALLBACK,
  );
  $items['agile_coursepack/browse'] = array(
    'description' => 'Coursepack content browsing page',
    'type' => MENU_CALLBACK,
    'page callback' => 'agile_coursepack_browse',
    'file' => 'includes/agile_coursepack_browse.inc',
    'access arguments' => array('access content'),
  );
  $items['agile_coursepack/coursepacks'] = array(
    'description' => 'Coursepack browsing page',
    'type' => MENU_CALLBACK,
    'page callback' => 'agile_coursepack_coursepack_browse',
    'file' => 'includes/agile_coursepack_browse.inc',
    'access arguments' => array('access content'),
  );
  $items['agile_coursepack/populate'] = array(
    'description' => 'Populate coursepack',
    'type' => MENU_CALLBACK,
    'page callback' => 'agile_populate_coursepack',
    'file' => 'includes/utilities.inc',
    'access arguments' => array('access content'),
  );
  $items['agile_coursepack/consolidate'] = array(
    'title' => 'Download Zip',
    'description' => 'Download coursepack PDFs.',
    'page callback' => 'agile_coursepack_download',
    'access arguments' => array('access content'),
    'file' => 'includes/utilities.inc',
    'type' => MENU_CALLBACK,
  );
  $items['agile_coursepack/clone'] = array(
    'title' => 'Duplicate existing coursepack',
    'description' => 'Copy Coursepack for modification',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('agile_coursepack_clone_form'),
    'file' => 'includes/agile_coursepack_clone.form.inc',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );


  return $items;
}

/**
 * Implements hook_theme().
 */
function agile_coursepack_theme($existing, $type, $theme, $path) {
  return array(
    'agile_coursepack' => array(
      'template' => 'theme/agile_coursepack',
      'file' => 'theme/theme.inc',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function agile_coursepack_permission() {
  return array(
    'create new coursepacks' => array(
      'title' => t('Create New Coursepacks'),
      'description' => t('Allows users to create anthologies'),
    ),
    'edit coursepacks' => array(
      'title' => t('Create New Coursepacks'),
      'description' => t('Allows users to create anthologies'),
    ),
    'add source content' => array(
      'title' => t('Add new content'),
      'description' => t('Allows users to upload content'),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function agile_coursepack_islandora_required_objects(IslandoraTuque $connection) {
  module_load_include('inc', 'agile_coursepack', 'includes/required_objects');
  return agile_coursepack_get_required_objects($connection);
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function agile_coursepack_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'agile_coursepack');
  return array(
    'Coursepack MODS form' => array(
      'form_file' => "$module_path/xml/agile_coursepack_form.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function agile_coursepack_islandora_xml_form_builder_form_associations() {
  return array(
    'agile_coursepack_mods_form' => array(
      'content_model' => 'islandora:coursepackCModel',
      'form_name' => 'Coursepack MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_cmodel_islandora_view_object().
 */
function agile_coursepack_islandora_coursepackCModel_islandora_view_object($object) {
  if (!$object['OBJ']) {
    return t('No description available');
  }
  $output = theme('agile_coursepack', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function agile_coursepack_islandora_coursepackCModel_islandora_ingest_steps() {
  return array(
    'agile_coursepack_file_upload' => array(
      'weight' => -50,
      'type' => 'form',
      'form_id' => 'agile_coursepack_document_upload_form',
      'module' => 'agile_coursepack',
      'file' => 'includes/agile_coursepack.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_derivative().
 */
function agile_coursepack_islandora_coursepackCModel_islandora_derivative() {
  module_load_include('module', 'islandora_document');
  return islandora_document_islandora_sp_document_islandora_derivative();
}

/**
 * Implements hook_islandora_solr_primary_display().
 */
function agile_coursepack_islandora_solr_primary_display() {
  return array(
    'coursepack' => array(
      'name' => t('Add Selected Results to Coursepack'),
      'module' => 'agile_coursepack',
      'file' => 'includes/coursepack_results.inc',
      'class' => "IslandoraSolrResultsCoursepack",
      'function' => "displayResults",
      'description' => t("Add Selected Results to Coursepack"),
    ),
    'coursepack_default_display' => array(
      'name' => t('Coursepack Solr Results'),
      'module' => 'agile_coursepack',
      'file' => 'includes/coursepack_solr_display.inc',
      'class' => "IslandoraSolrResultsCoursepackDisplay",
      'function' => "displayResults",
      'description' => t("Default Coursepack Display"),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function agile_coursepack_form_islandora_solr_advanced_search_form_alter(&$form, &$form_state, $form_id) {
  module_load_include('inc', 'agile_coursepack', 'includes/utilities');
  $coursepack_pid = agile_coursepack_get_pid_from_url();
  if (user_access('edit coursepacks') && $coursepack_pid) {
    $form_state['coursepack_pid'] = $coursepack_pid;
    $form_state['redirect'] = "islandora/object/$coursepack_pid";

    $form['coursepack'] = array(
      '#type' => 'checkbox',
      '#title' => t('Coursepack selection?'),
    );
    $form['#submit'][0] = 'agile_coursepack_advanced_solr_search_form_submit';
  }
}

/**
 * Implements hook_form_alter().
 */
function agile_coursepack_form_islandora_solr_simple_search_form_alter(&$form, &$form_state) {
  if (isset($_GET['q']) && strpos($_GET['q'], 'agile_coursepack/browse') === 0) {
    $form['#submit'][0] = 'agile_coursepack_solr_search_form_submit';
  }
}

/**
 * Islandora Solr simple search form submit callback.
 *
 * @param array $form
 *   An associative array containing form structure.
 * @param array $form_state
 *   An associative array containing form state.
 */
function agile_coursepack_solr_search_form_submit($form, &$form_state) {
  $search_string = str_replace('/', '~slsh~', $form_state['values']['islandora_simple_search_query']);
  $filter = 'RELS_EXT_hasModel_uri_s:"info:fedora/islandora:sp_videoCModel" OR RELS_EXT_hasModel_uri_s:"info:fedora/islandora:sp-audioCModel" OR RELS_EXT_hasModel_uri_s:"info:fedora/islandora:sp_basic_image" OR RELS_EXT_hasModel_uri_s:"info:fedora/islandora:sp_large_image_cmodel" OR RELS_EXT_hasModel_uri_s:"info:fedora/islandora:islandora:sp_document"';
  $options = array('query' => array('type' => 'dismax', 'fq' => $filter));
  drupal_goto('agile_coursepack/browse/' . $search_string, $options);
}

/**
 * Islandora Solr simple search form submit callback.
 *
 * @param array $form
 *   An associative array containing form structure.
 * @param array $form_state
 *   An associative array containing form state.
 */
function agile_coursepack_advanced_solr_search_form_submit($form, &$form_state) {
// Collect query values.
  $query_array = array();
  foreach ($form_state['values']['terms'] as $term) {
    $field = $term['field'];
    $search = trim($term['search']);
// XXX: Should probably use islandora_solr_replace_slashes().
    $search = str_replace('/', '~slsh~', $search);
    $boolean = (isset($term['boolean'])) ? $term['boolean'] : variable_get('islandora_solr_search_boolean', 'user');

// Add query.
    if (!empty($search)) {
      $query_array[] = array(
        'search' => "$field:($search)",
        'boolean' => $boolean,
      );
    }
  }
// Create query.
  $query = '';
  $i = 0;
  foreach ($query_array as $term) {
    $query .= $term['search'];
    if (count($query_array) - 1 != $i) {
      $query .= ' ' . $term['boolean'] . ' ';
    }
    $i++;
  }

// Check if query is empty.
  if (empty($query)) {
    $query = '*:*';
  }
  $options = array();
  if ($form_state['values']['coursepack']) {
    $options['query']['display'] = 'coursepack';
    $options['query']['pid'] = $form_state['coursepack_pid'];
  }
// Navigate to results page.
  // drupal_goto('islandora/search/' . $query, $options);
}

/**
 * Implements hook_block_view_alter().
 */
function agile_coursepack_block_view_alter_x(&$data, $block) {
  module_load_include('inc', 'agile_coursepack', 'includes/utilities');
  $coursepack_pid = agile_coursepack_get_pid_from_url();
  if ($coursepack_pid && isset($data['subject']) && $data['subject'] == 'Islandora simple search') {
    $object = islandora_object_load($coursepack_pid);
    $data['subject'] = t("Add digital assets to @label", array('@label' => $object->label));
    $block->visibility = TRUE;
  }
}

/**
 * Implements hook_block_info().
 */
function agile_coursepack_block_info() {
  $blocks['coursepack_solr'] = array(
    'info' => t('Solr Builder for Coursepacks'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function agile_coursepack_block_view($delta = '') {
  module_load_include('inc', 'agile_coursepack', 'includes/solr_forms');
  $has_content = FALSE;
  switch ($delta) {
    case 'coursepack_solr':
      $block['content'] = drupal_get_form('agile_coursepack_search_form');
      break;
  }

  return $block;
}

/**
 * Implements hook_islandora_solr_query().
 */
function agile_coursepack_islandora_solr_query($islandora_solr_query) {

  if (isset($_GET['q']) && strpos($_GET['q'], 'agile_coursepack/browse') === 0) {
    $filters[] = 'RELS_EXT_hasModel_uri_s:"info:fedora/islandora:sp_document"';
    $filters[] .= 'RELS_EXT_hasModel_uri_s:"info:fedora/islandora:sp_large_image_cmodel"';
    $filters[] .= 'RELS_EXT_hasModel_uri_s:"info:fedora/islandora:sp-audioCModel"';
    $filters[] .= 'RELS_EXT_hasModel_uri_s:"info:fedora/islandora:sp_videoCModel"';
    $filter = implode(' OR ', $filters);
    $islandora_solr_query->solrParams['fq'][] = $filter;
  }
  if (isset($_GET['q']) && strpos($_GET['q'], 'agile_coursepack/coursepacks') === 0) {
    $filter = 'RELS_EXT_hasModel_uri_s:"info:fedora/islandora:coursepackCModel"';
    $islandora_solr_query->solrParams['fq'][] = $filter;
  }
}

function agile_coursepack_form_islandora_compound_object_manage_form_alter(&$form, &$form_state, $form_id){
  $pid = $form_state['object']->id;
  $link = l(t('Return to coursepack view'),"islandora/object/$pid");
  $form['view'] = array(
    '#markup' => $link,
    '#weight' => -5,
  );
}